language: java
jdk: oraclejdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
after_success: ".travis/notify.sh Travis-Success"
after_failure: ".travis/notify.sh Travis-Failure"
env:
  global:
  - secure: ZUIqer1xroMRkLsUgz/Vihb3ji7jR6mJy1096/k22GxsjNvajBcQ8mmDMv1TghmvjKdjxt3awTsoWn3o6K+e9J6+pbxADebwKRhuNXI0ND3brZM2/oadvNDb1cF1/nzFTdeJjDGbi3USSwMEObYTd2fcTV5majHTyPaxDDreot4=
  - secure: ZYppQ51VSbEpesuQi49DkDGA/glnuI6dgUAbYFc4DtRqmGMNN6kuOZmmoPhxM1ofLde/Z+q+oxeVcpY2mTgsbCPcuksYVaZw3YG8heUiCEMApQVdkk4+ReYaH3ROHQjsfHc9Q3LDUpnmEHU7ZTEnBtxz8Gv9Q8aQl2OJJjXdaz0=
